DEFINE VARIABLE vPath AS CHARACTER NO-UNDO.
DEFINE VARIABLE vLine AS CHARACTER NO-UNDO.

vPath = "env/settings.cfg".

INPUT FROM VALUE(vPath).

REPEAT:
IMPORT UNFORMATTED vLine.
DISPLAY vLine.
END.

INPUT CLOSE.